import 'dart:io';

class ReadMeModifier {
  static Future<void> modify({required String projectName}) async {
    try {
      // Read the current content of the README.md file
      String projectPath = '${Directory.current.path}/$projectName';
      final readMePath = '$projectPath/README.md';
      final readMeFile = File(readMePath);
      // Modify the content as needed
      var content = """
# $projectName

This project generated by gen_helper written by iamtechie (Abduvakhobov Isroiljon).

Project used Clean Architecture design pattern.

## Features
Project is ready to modify and add new features.

Here some other essential commands to help you: 

-- Generate new feature =>
  \$ generate feature

- Regenerate LocaleKeys =>
  \$ dart run easy_localization:generate -S "assets/translations" -O "lib/generated" & dart run easy_localization:generate -S "assets/translations" -O "lib/generated" -o "locale_keys.g.dart" -f keys

- Rebuild build files =>
  \$ flutter pub run build_runner build --delete-conflicting-outputs
 
            
      """;

      // Write the updated content back to the README.md file
      readMeFile.writeAsStringSync(content);

      print('README.md file updated successfully.');
    } catch (e) {
      print('Error updating README.md file: $e');
    }
  }
}
